### ISSUE TITLE
Import GRCh38 reference genome.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#14]
GRCh38 reference FASTA with index and sequence dictionary:

> /gscmnt/gc9005/info/model_data/2887491634/build4ec1c5bd1f6941b8a99f2e230217cb91/all_sequences.fa
/gscmnt/gc9005/info/model_data/2887491634/build4ec1c5bd1f6941b8a99f2e230217cb91/all_sequences.dict
/gscmnt/gc9005/info/model_data/2887491634/build4ec1c5bd1f6941b8a99f2e230217cb91/all_sequences.fa.fai

**Comment by tmooney** [comment]
These have been uploaded to my home project.
