### ISSUE TITLE
Test new MGI group for sharing.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#26]
@tmooney could you share some of the collections using the new MGI group?

**Comment by tmooney** [comment]
I shared the project "DV-WGS" on Thursday. I've updated the permissions from "Read" to "Manage", so I think that should give the MGI group a fair amount of control.  Are the collections inside it visible?

**Comment by jasonwalker80** [comment]
I can confirm the DV-WGS project was shared and I can see all data collections and pipeline instances.
