### ISSUE TITLE
Add VEP annotation to detect_variants.cwl workflow

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#31]

**Comment by jasonwalker80** [comment]
@susannasiebert Do we need to tie the new synonyms input back to the full workflow?  Is it an optional input to those workflows?

**Comment by susannasiebert** [comment]
Yes, we do. Sorry for the oversight. I will make a PR.

**Comment by jasonwalker80** [comment]
This exist in the toil_compatibility branch. closing.
