### ISSUE TITLE
Implement alignment strategy before detect_variants.cwl.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#33]
We should use this GRCh38DH reference to match CCDG:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/

UPDATE: Even better is, "This README explains the alignment pipeline used to remap all the 1000 Genomes Project Phase 3 reads to GRCh38DH.":
https://github.com/igsr/1000Genomes_data_indexes/blob/master/data_collections/1000_genomes_project/README.1000genomes.GRCh38DH.alignment

**Comment by jasonwalker80** [comment]
https://bitbucket.gsc.wustl.edu/projects/LIMS/repos/compute-work-flow/browse/wdl/Compute/UnalignedToMarkedBam/work_flow.wdl

For the raw WDL file:
https://bitbucket.gsc.wustl.edu/projects/LIMS/repos/compute-work-flow/browse/wdl/Compute/UnalignedToMarkedBam/work_flow.wdl?at=refs%2Fheads%2Fmaster&raw

**Comment by jasonwalker80** [comment]
@tmooney could you help point us to the WDL location in Bitbucket for the CCDG pipeline documented here:
https://confluence.gsc.wustl.edu/pages/viewpage.action?pageId=26968484

**Comment by tmooney** [comment]
The WDL for that one is here:
https://bitbucket.gsc.wustl.edu/projects/LIMS/repos/compute-work-flow/browse/wdl/Compute/UnalignedBamToBQSRandVCF/work_flow.wdl

**Comment by susannasiebert** [comment]
Which one of these two workflows is the one that we are interested in recreating?

**Comment by jasonwalker80** [comment]
From the meeting yesterday, it was decided that we should move forward with BQSR and CRAM support. So the latter, longer workflow, 'UnalignedBamToBQSRandVCF'.
