### ISSUE TITLE
Import HCC1395 Exome aligned BAM files.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#4]

**Comment by jasonwalker80** [comment]
Exome BAM Files:

> 5.6G	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.bam
35M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.discordants.bam
36M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.splitters.bam
5.8G	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.bam
37M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.discordants.bam
37M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.splitters.bam
12G	total

Exome BAM Index Files:
>6.7M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.bam.bai
4.5M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.discordants.bam.bai
4.1M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/normal/e49b770382734c61963cd0585bd4c468.splitters.bam.bai
6.7M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.bam.bai
4.5M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.discordants.bam.bai
3.7M	/gscmnt/gc13029/info/model_data/2183650f69494215a5af042da04becc2/build269da5c36a0b4dd6b9fff053b0c10956/alignments/tumor/31b28aca4ded4e93ac5f762aa3195b67.splitters.bam.bai
30M	total

**Comment by jasonwalker80** [comment]
@tmooney see the previous comment for internal HCC1395 BAM locations.

**Comment by tmooney** [comment]
I've uploaded these to my home project on Curoverse.  If anyone else needs access to the files there appears to be a UI for "sharing" my collections.
