### ISSUE TITLE
Add synonyms input

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#45]
Define a synonyms input file to map chromosome names between GRCh38DH and Ensembl.

**Comment by jasonwalker80** [comment]
This file should work for synonyms:
`wget --no-check-certificate http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromAlias.txt.gz`

We should probably grep for 'ensembl' instead of providing all synonyms/aliases.

**Comment by susannasiebert** [comment]
Where do you want me to save this file?

**Comment by jasonwalker80** [comment]
Eventually it would need to be an input defined in a yaml file.  CWL would have to be updated to support the optional input.  

The file itself would need to be uploaded to keep.  Here is a rough doc for transferring data to our local open stack/arvados cluster: 
https://confluence.gsc.wustl.edu/display/CI/Arvados+OpenStack+Cluster#ArvadosOpenStackCluster-DataTransfer

**Comment by jasonwalker80** [comment]
adding the input is finished.
