### ISSUE TITLE
Use VEP from github rather than ensembl-tools

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#48]
It's currently labeled as beta; however, the latest ensembl release 87 is the last release where the ensembl-tools version of VEP will be updated.  Future updates and releases of the VEP software will be independent and the software can be installed directly from Github rather than through the ensembl-tools.

https://github.com/Ensembl/ensembl-vep

**Comment by susannasiebert** [comment]
New PRs for release 87 are [here](https://github.com/genome/docker-vep/pull/4) and [here](https://github.com/genome/docker-vep-cwl/pull/3).
